"""Named database contracts. Each RPC operation has a real-transport budget test."""

from typing import Any, Protocol

Row = dict[str, Any]


class GitTransport(Protocol):
    """Run-bound smart HTTP and metadata; no file/object storage capability."""

    def describe(self, project: str, grant: Any) -> Row: ...
    def result(self, project: str, grant: Any, request_key: str) -> Row | None: ...
    async def exchange(
        self, project: str, grant: Any, frame: Row, *, base: Row, publication: Any = None
    ) -> Row: ...


class RenewalPort(Protocol):
    def renew_execution(self, run: Row) -> Row: ...


class RunQueries(Protocol):
    def surface(self, agent_id: str) -> Row | None: ...
    def load_history_view(
        self, user: str, project: str, agent: str, limit: int = 50
    ) -> Row | None: ...
    def load_run_context(
        self,
        user: str,
        project: str,
        agent: str | None = None,
        scope: str | None = None,
        request: str | None = None,
    ) -> Row: ...
    def load_run_view(self, user: str, run: str, after: int = 0) -> Row | None: ...
    def load_execution(self, run: str) -> Row: ...
    def load_receipt_view(self, user: str, project: str, request: str) -> Row | None: ...
    def load_session_view(
        self, user: str, session: str, limit: int = 50, before: Any = None
    ) -> Row | None: ...
    def get(self, run_id: str) -> Row | None: ...
    def receipt(self, user: str, project: str, request: str) -> Row | None: ...
    def tools(self, run_id: str) -> list[Row]: ...
    def executions(self, run_id: str) -> list[Row]: ...
    def session_runs(
        self, user_id: str, session_id: str, limit: int, before: Any = None
    ) -> list[Row]: ...


class RunStore(RunQueries, RenewalPort, Protocol):
    def settle_model(self, run: Row, *, checkpoint: Row) -> Row: ...
    def start_execution(self, run: Row, *, checkpoint: Row, billing: str, resource: Row) -> Row: ...
    def begin_model(self, run: Row, *, request: str, checkpoint: Row, limit: int) -> Row: ...
    def begin_tool(self, run: Row, frame: Row, *, checkpoint: Row, mutation: bool) -> Row: ...
    def complete_tool(self, run: Row, frame: Row, *, result: Row, checkpoint: Row) -> Row: ...
    def submit_run(self, **values: Any) -> Row: ...
    def claim_run(self, *, worker: str) -> Row | None: ...
    def create_builtin(
        self, *, project: str, scope: str | None, user: str, config: Row, revision: Row
    ) -> str: ...
    def command_run(self, *, run: str, user: str, command: str, **values: Any) -> Row: ...
    def append_events_batch(self, run: Row, events: list[Row], *, batch_id: str) -> Row: ...
    def write(self, run: Row, kind: str, payload: Row | None = None, **patch: Any) -> Row: ...
    def tool(self, run: Row, frame: Row, state: str, result: Row | None = None) -> Row: ...
    def cleaned(self, execution_id: str) -> None: ...
    def complete_run(
        self, run: Row, *, state: str, code: str, snapshot: Row, cleaned: bool = False
    ) -> Row: ...
